"""empty message

Revision ID: 7b09e8a8a8c9
Revises: 2bddf817646d
Create Date: 2024-05-14 18:14:53.092423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b09e8a8a8c9'
down_revision = '2bddf817646d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_code', sa.String(length=8), nullable=False))

    with op.batch_alter_table('study_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_code', sa.String(length=8), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_group', schema=None) as batch_op:
        batch_op.drop_column('unit_code')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('unit_code')

    # ### end Alembic commands ###
